version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: UFC_DB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
